import Foundation
import UIKit

// MARK: - Base Protocol
protocol FavoriteItem {
    var id: String { get }
    var title: String { get }
    var imageName: String { get }
    var description: String { get }
    var review: String { get }
}

// MARK: - Movie Model
struct Movie: FavoriteItem {
    let id: String
    let title: String
    let imageName: String
    let description: String
    let review: String
    let year: Int
    let genre: String
}

// MARK: - Music Model
struct Music: FavoriteItem {
    let id: String
    let title: String
    let imageName: String
    let description: String
    let review: String
    let artist: String
    let album: String
}

// MARK: - Book Model
struct Book: FavoriteItem {
    let id: String
    let title: String
    let imageName: String
    let description: String
    let review: String
    let author: String
    let pages: Int
}

// MARK: - Course Model
struct Course: FavoriteItem {
    let id: String
    let title: String
    let imageName: String
    let description: String
    let review: String
    let instructor: String
    let duration: String
}

// MARK: - Sample Data
struct SampleData {
    
    static let movies: [Movie] = [
        Movie(id: "1", title: "The Shawshank Redemption", imageName: "film", description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency. Andy Dufresne, a banker wrongly convicted of murder, maintains his innocence while forming an unlikely friendship with Red, a fellow inmate.", review: "An absolute masterpiece! The storytelling is perfect and the acting is phenomenal. Morgan Freeman and Tim Robbins deliver career-best performances. A must-watch film that never gets old.", year: 1994, genre: "Drama"),
        Movie(id: "2", title: "The Dark Knight", imageName: "film", description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice. Heath Ledger's iconic performance redefined comic book villains.", review: "Christopher Nolan crafted the best superhero movie ever made. Heath Ledger's Joker is unforgettable and terrifying. The action sequences are incredible and the moral dilemmas are thought-provoking.", year: 2008, genre: "Action"),
        Movie(id: "3", title: "Inception", imageName: "film", description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O. The film explores multiple layers of dreams within dreams, creating a complex narrative.", review: "Mind-bending and visually stunning! Nolan's most ambitious film that keeps you guessing until the very end. The dream sequences are beautifully crafted and the soundtrack is epic.", year: 2010, genre: "Sci-Fi"),
        Movie(id: "4", title: "Pulp Fiction", imageName: "film", description: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption. Tarantino's non-linear narrative style creates a unique cinematic experience.", review: "Tarantino at his absolute best! The dialogue is sharp, witty, and memorable. Every scene is iconic and the soundtrack is perfect. A film that defined a generation of cinema.", year: 1994, genre: "Crime"),
        Movie(id: "5", title: "Forrest Gump", imageName: "film", description: "The presidencies of Kennedy and Johnson, the Vietnam War, and other historical events unfold from the perspective of an Alabama man with an IQ of 75. His journey through life is both heartwarming and inspirational.", review: "Tom Hanks delivers one of the greatest performances ever. The film is emotional, funny, and uplifting. 'Life is like a box of chocolates' - this quote alone defines the movie's charm.", year: 1994, genre: "Drama"),
        Movie(id: "6", title: "The Matrix", imageName: "film", description: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers. The film revolutionized action cinema with its groundbreaking visual effects.", review: "Revolutionary filmmaking! The action sequences were ahead of their time and the philosophical themes are still relevant today. Keanu Reeves was born to play Neo.", year: 1999, genre: "Sci-Fi"),
        Movie(id: "7", title: "Interstellar", imageName: "film", description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival. The film combines hard science fiction with emotional storytelling about love transcending time and space.", review: "Christopher Nolan's most emotional film. The science is fascinating and the visuals are breathtaking. Matthew McConaughey's performance is powerful and the ending brought me to tears.", year: 2014, genre: "Sci-Fi"),
        Movie(id: "8", title: "Goodfellas", imageName: "film", description: "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito. Based on true events, the film spans several decades.", review: "Scorsese's masterpiece of organized crime cinema. The pacing is perfect and every actor brings their A-game. Joe Pesci is absolutely terrifying as Tommy.", year: 1990, genre: "Crime"),
        Movie(id: "9", title: "Parasite", imageName: "film", description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan. This South Korean masterpiece won the Oscar for Best Picture.", review: "A brilliant social commentary wrapped in a thrilling narrative. Bong Joon-ho created something truly unique that keeps you on edge from start to finish. Deserved all the awards it won!", year: 2019, genre: "Thriller"),
        Movie(id: "10", title: "The Godfather", imageName: "film", description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son. The film is considered one of the greatest films ever made, exploring themes of power, family, and loyalty.", review: "The definition of perfect cinema. Marlon Brando and Al Pacino are legendary. Every frame is meticulously crafted and the storytelling is unmatched. A timeless classic that set the standard.", year: 1972, genre: "Crime")
    ]
    
    static let music: [Music] = [
        Music(id: "1", title: "Bohemian Rhapsody", imageName: "music.note", description: "An epic rock ballad that defies conventional song structure. Freddie Mercury's masterpiece combines opera, rock, and ballad into a six-minute journey. The song showcases Queen's musical versatility and Mercury's incredible vocal range.", review: "One of the greatest songs ever written! The vocal harmonies are absolutely stunning and the structure is revolutionary. It never gets old no matter how many times I listen to it.", artist: "Queen", album: "A Night at the Opera"),
        Music(id: "2", title: "Hotel California", imageName: "music.note", description: "A metaphorical journey through excess and loss of innocence in 1970s California. The iconic guitar solo is considered one of the best in rock history. The song's mysterious lyrics have been interpreted in countless ways.", review: "The guitar work is absolutely phenomenal! Don Henley's vocals perfectly capture the dark atmosphere. That dual guitar solo at the end gives me goosebumps every single time.", artist: "Eagles", album: "Hotel California"),
        Music(id: "3", title: "Imagine", imageName: "music.note", description: "John Lennon's anthem for peace and unity invites listeners to envision a world without borders, religions, or possessions. The simple piano melody supports profound and hopeful lyrics about human harmony.", review: "A timeless message of peace that's still relevant today. Lennon's sincerity shines through every word. The simplicity of the arrangement makes the message even more powerful.", artist: "John Lennon", album: "Imagine"),
        Music(id: "4", title: "Smells Like Teen Spirit", imageName: "music.note", description: "The song that defined a generation and brought grunge into mainstream consciousness. Kurt Cobain's raw vocals and the explosive chorus captured teenage angst and rebellion perfectly.", review: "The anthem of the 90s! The energy is explosive and Kurt's voice is raw and powerful. This song changed rock music forever and still sounds fresh today.", artist: "Nirvana", album: "Nevermind"),
        Music(id: "5", title: "Billie Jean", imageName: "music.note", description: "Michael Jackson's signature song features an unforgettable bassline and production by Quincy Jones. The track addresses themes of fame and false accusations, becoming one of the best-selling singles of all time.", review: "That bassline is instantly recognizable! Michael's vocal performance is flawless and the production is ahead of its time. The King of Pop at his absolute best.", artist: "Michael Jackson", album: "Thriller"),
        Music(id: "6", title: "Sweet Child O' Mine", imageName: "music.note", description: "Guns N' Roses' breakthrough hit features Slash's iconic guitar riff that ranks among rock's most recognizable openings. Axl Rose's passionate vocals tell a love story with raw emotion.", review: "Slash's guitar intro is legendary! Axl's voice soars on this track and the energy is incredible. One of the best rock love songs ever written.", artist: "Guns N' Roses", album: "Appetite for Destruction"),
        Music(id: "7", title: "Wonderwall", imageName: "music.note", description: "Oasis's signature song became a cultural phenomenon in the 90s. Noel Gallagher's songwriting captures longing and hope with simple yet effective chord progressions and memorable melodies.", review: "The anthem of the Britpop era! Everyone knows the words and it's perfect for sing-alongs. Liam's voice and Noel's songwriting create magic together.", artist: "Oasis", album: "(What's the Story) Morning Glory?"),
        Music(id: "8", title: "Stairway to Heaven", imageName: "music.note", description: "Led Zeppelin's epic eight-minute masterpiece builds from a gentle acoustic opening to a powerful electric climax. Jimmy Page's guitar solo is considered one of the greatest ever recorded.", review: "The ultimate rock song! The progression from acoustic to electric is perfectly executed. Jimmy Page's solo is transcendent and Robert Plant's vocals are incredible.", artist: "Led Zeppelin", album: "Led Zeppelin IV"),
        Music(id: "9", title: "Hallelujah", imageName: "music.note", description: "Leonard Cohen's spiritual ballad has been covered countless times, but each version brings new meaning. The song explores faith, love, and loss through biblical references and personal reflection.", review: "Leonard Cohen's poetry at its finest. Jeff Buckley's cover is hauntingly beautiful. The lyrics are profound and the melody is timeless. A song that touches the soul.", artist: "Leonard Cohen", album: "Various Positions"),
        Music(id: "10", title: "Like a Rolling Stone", imageName: "music.note", description: "Bob Dylan's revolutionary six-minute single changed the landscape of popular music. The song's biting lyrics and organ-driven sound broke conventions and influenced generations of musicians.", review: "Dylan's greatest moment! The lyrics are sharp and poetic, and Al Kooper's organ work is iconic. 'How does it feel?' - that question still resonates today.", artist: "Bob Dylan", album: "Highway 61 Revisited")
    ]
    
    static let books: [Book] = [
        Book(id: "1", title: "1984", imageName: "book", description: "George Orwell's dystopian masterpiece depicts a totalitarian society under constant surveillance. The story follows Winston Smith as he rebels against the Party and Big Brother. The novel explores themes of truth, freedom, and the power of language.", review: "A chilling and prophetic vision of totalitarianism. Orwell's warnings about surveillance and propaganda are more relevant than ever. The concept of 'doublethink' and 'newspeak' brilliantly illustrates how language shapes reality.", author: "George Orwell", pages: 328),
        Book(id: "2", title: "To Kill a Mockingbird", imageName: "book", description: "Harper Lee's powerful novel about racial injustice in the American South. Through Scout Finch's eyes, we witness her father Atticus defend a black man falsely accused of rape. The story explores prejudice, morality, and childhood innocence.", review: "A timeless classic that everyone should read. Atticus Finch is the embodiment of integrity and courage. The narrative beautifully balances childhood wonder with serious social commentary.", author: "Harper Lee", pages: 324),
        Book(id: "3", title: "The Great Gatsby", imageName: "book", description: "F. Scott Fitzgerald's Jazz Age masterpiece explores the American Dream through Jay Gatsby's pursuit of Daisy Buchanan. Set in 1920s New York, the novel critiques wealth, class, and the illusion of happiness through material success.", review: "Fitzgerald's prose is absolutely beautiful. The symbolism of the green light and the valley of ashes is brilliant. A tragic tale about the impossibility of recapturing the past.", author: "F. Scott Fitzgerald", pages: 180),
        Book(id: "4", title: "Harry Potter and the Philosopher's Stone", imageName: "book", description: "The magical journey begins as Harry Potter discovers he's a wizard and attends Hogwarts School of Witchcraft and Wizardry. J.K. Rowling creates an enchanting world filled with memorable characters and adventures.", review: "The book that started it all! Rowling's world-building is incredible and the characters feel like old friends. It's not just a children's book - it's a story about love, friendship, and standing up to evil.", author: "J.K. Rowling", pages: 223),
        Book(id: "5", title: "Pride and Prejudice", imageName: "book", description: "Jane Austen's romantic novel follows Elizabeth Bennet's complicated relationship with Mr. Darcy. Set in Georgian England, the story brilliantly satirizes social class and the marriage market while delivering timeless romance.", review: "Austen's wit is unmatched! Elizabeth Bennet is one of literature's greatest heroines. The dialogue sparkles and the social commentary is still relevant. Mr. Darcy's character development is perfection.", author: "Jane Austen", pages: 432),
        Book(id: "6", title: "The Lord of the Rings", imageName: "book", description: "J.R.R. Tolkien's epic fantasy follows Frodo Baggins's quest to destroy the One Ring. The richly detailed Middle-earth features diverse races, languages, and histories. The story explores friendship, sacrifice, and the corruption of power.", review: "The foundation of modern fantasy! Tolkien's world-building is unparalleled in its depth and detail. The fellowship's journey is epic in every sense. Sam Gamgee is the true hero of the story.", author: "J.R.R. Tolkien", pages: 1178),
        Book(id: "7", title: "The Catcher in the Rye", imageName: "book", description: "J.D. Salinger's coming-of-age novel follows Holden Caulfield through New York City after being expelled from prep school. His cynical voice captures teenage alienation and the struggle between childhood and adulthood.", review: "Holden's voice is authentic and relatable. Salinger perfectly captures teenage angst and disillusionment. The novel's themes of identity and belonging still resonate with readers today.", author: "J.D. Salinger", pages: 234),
        Book(id: "8", title: "One Hundred Years of Solitude", imageName: "book", description: "Gabriel García Márquez's magical realist epic chronicles the Buendía family across seven generations in the fictional town of Macondo. The novel blends reality with fantasy, exploring themes of time, memory, and solitude.", review: "A masterpiece of magical realism! Márquez's storytelling is mesmerizing and the cyclical nature of the Buendía family's history is fascinating. The prose is beautiful and dreamlike.", author: "Gabriel García Márquez", pages: 417),
        Book(id: "9", title: "The Hobbit", imageName: "book", description: "Bilbo Baggins's unexpected journey from his comfortable hobbit-hole to the Lonely Mountain. Tolkien's adventure story features trolls, goblins, elves, and a dragon, while teaching valuable lessons about courage and personal growth.", review: "A perfect adventure story! Bilbo's transformation from reluctant hobbit to brave adventurer is inspiring. The riddle game with Gollum is unforgettable. A great introduction to Middle-earth.", author: "J.R.R. Tolkien", pages: 310),
        Book(id: "10", title: "The Alchemist", imageName: "book", description: "Paulo Coelho's philosophical novel follows Santiago, a shepherd boy, on his journey to find treasure in Egypt. The story explores personal legends, following dreams, and finding one's true purpose through a mystical adventure.", review: "An inspiring tale about following your dreams! Coelho's writing is simple yet profound. The concept of Personal Legend resonates deeply and the lessons about listening to your heart are timeless.", author: "Paulo Coelho", pages: 208)
    ]
    
    static let courses: [Course] = [
        Course(id: "1", title: "iOS Development Complete Course", imageName: "graduationcap", description: "Master iOS development from basics to advanced topics. Learn Swift programming, UIKit, SwiftUI, Core Data, networking, and more. Build real-world applications including weather apps, social media clones, and productivity tools.", review: "Incredibly comprehensive course! The instructor explains complex concepts clearly and the projects are practical. After completing this, I feel confident building my own iOS apps from scratch.", instructor: "Angela Yu", duration: "60 hours"),
        Course(id: "2", title: "Machine Learning A-Z", imageName: "graduationcap", description: "Comprehensive machine learning course covering supervised and unsupervised learning, neural networks, and deep learning. Uses Python, scikit-learn, and TensorFlow. Includes hands-on projects with real datasets.", review: "The best ML course I've taken! Complex algorithms are broken down into understandable concepts. The practical projects helped solidify my understanding. Perfect for both beginners and intermediate learners.", instructor: "Kirill Eremenko", duration: "44 hours"),
        Course(id: "3", title: "The Complete Web Developer Bootcamp", imageName: "graduationcap", description: "Learn full-stack web development including HTML, CSS, JavaScript, React, Node.js, MongoDB, and more. Build responsive websites and web applications. Covers modern development practices and deployment.", review: "Amazing value for money! Covers everything needed to become a full-stack developer. The projects are engaging and the instructor's teaching style makes learning enjoyable. Highly recommended for beginners.", instructor: "Colt Steele", duration: "63 hours"),
        Course(id: "4", title: "Data Science with Python", imageName: "graduationcap", description: "Master data science using Python, Pandas, NumPy, Matplotlib, and Seaborn. Learn data analysis, visualization, and statistical methods. Work on real-world datasets and case studies.", review: "Excellent practical approach to data science! The projects use real datasets which makes learning relevant. The instructor's explanations of statistical concepts are clear and easy to follow.", instructor: "Jose Portilla", duration: "25 hours"),
        Course(id: "5", title: "The Complete Digital Marketing Course", imageName: "graduationcap", description: "Comprehensive digital marketing training covering SEO, social media marketing, email marketing, Google Ads, and analytics. Learn strategies to grow businesses online and measure campaign success.", review: "Super practical course with actionable strategies! Covers all aspects of digital marketing thoroughly. The real-world examples and case studies make it easy to apply concepts to actual campaigns.", instructor: "Rob Percival", duration: "23 hours"),
        Course(id: "6", title: "AWS Certified Solutions Architect", imageName: "graduationcap", description: "Prepare for the AWS Solutions Architect certification. Learn about AWS services including EC2, S3, RDS, Lambda, and more. Understand cloud architecture best practices and design scalable solutions.", review: "The best AWS prep course available! The instructor's explanations are crystal clear and the hands-on labs are invaluable. Passed the certification on my first attempt thanks to this course!", instructor: "Stephane Maarek", duration: "27 hours"),
        Course(id: "7", title: "JavaScript: The Advanced Concepts", imageName: "graduationcap", description: "Deep dive into JavaScript covering closures, prototypes, this keyword, async programming, and functional programming. Learn how JavaScript works under the hood to become an expert developer.", review: "Mind-blowing! This course transformed my understanding of JavaScript. Finally understood closures, prototypes, and the event loop. The instructor makes complex topics accessible and interesting.", instructor: "Andrei Neagoie", duration: "25 hours"),
        Course(id: "8", title: "Complete Python Developer", imageName: "graduationcap", description: "Learn Python from zero to advanced including OOP, functional programming, decorators, generators, testing, and more. Build 12+ projects including web scrapers, automation tools, and games.", review: "The most complete Python course out there! Projects are fun and practical. The instructor keeps things interesting while covering deep technical concepts. Great for career changers.", instructor: "Andrei Neagoie", duration: "30 hours"),
        Course(id: "9", title: "React - The Complete Guide", imageName: "graduationcap", description: "Master React including hooks, context, Redux, React Router, Next.js, and TypeScript. Build modern, responsive web applications with best practices. Includes testing and deployment strategies.", review: "Outstanding React course! Maximilian is an excellent teacher who explains concepts thoroughly. The course is constantly updated with new React features. The projects are portfolio-worthy.", instructor: "Maximilian Schwarzmüller", duration: "49 hours"),
        Course(id: "10", title: "Docker and Kubernetes Complete Guide", imageName: "graduationcap", description: "Master containerization and orchestration using Docker and Kubernetes. Learn to build, deploy, and scale applications. Covers CI/CD pipelines, microservices architecture, and cloud deployment.", review: "Excellent hands-on course! The practical approach helps understand Docker and Kubernetes quickly. The multi-container projects are especially valuable. Essential for modern DevOps practices.", instructor: "Stephen Grider", duration: "22 hours")
    ]
}
